package com.dv.moneym.core.model

val PopularCurrencyCodes = listOf("USD", "EUR", "GBP", "JPY", "CHF", "CAD", "AUD", "CNY")

val CommonCurrencies = listOf(
    CurrencyInfo("USD", "US Dollar", "$", "United States"),
    CurrencyInfo("EUR", "Euro", "€", "Eurozone"),
    CurrencyInfo("GBP", "British Pound", "£", "United Kingdom"),
    CurrencyInfo("JPY", "Japanese Yen", "¥", "Japan"),
    CurrencyInfo("CHF", "Swiss Franc", "CHF", "Switzerland"),
    CurrencyInfo("CAD", "Canadian Dollar", "CA$", "Canada"),
    CurrencyInfo("AUD", "Australian Dollar", "A$", "Australia"),
    CurrencyInfo("CNY", "Chinese Yuan", "¥", "China"),
    CurrencyInfo("HKD", "Hong Kong Dollar", "HK$", "Hong Kong"),
    CurrencyInfo("SGD", "Singapore Dollar", "S$", "Singapore"),
    CurrencyInfo("SEK", "Swedish Krona", "kr", "Sweden"),
    CurrencyInfo("NOK", "Norwegian Krone", "kr", "Norway"),
    CurrencyInfo("DKK", "Danish Krone", "kr", "Denmark"),
    CurrencyInfo("NZD", "New Zealand Dollar", "NZ$", "New Zealand"),
    CurrencyInfo("MXN", "Mexican Peso", "MX$", "Mexico"),
    CurrencyInfo("BRL", "Brazilian Real", "R$", "Brazil"),
    CurrencyInfo("INR", "Indian Rupee", "₹", "India"),
    CurrencyInfo("KRW", "South Korean Won", "₩", "South Korea"),
    CurrencyInfo("ZAR", "South African Rand", "R", "South Africa"),
    CurrencyInfo("TRY", "Turkish Lira", "₺", "Turkey"),
    CurrencyInfo("PLN", "Polish Zloty", "zł", "Poland"),
    CurrencyInfo("CZK", "Czech Koruna", "Kč", "Czech Republic"),
    CurrencyInfo("HUF", "Hungarian Forint", "Ft", "Hungary"),
    CurrencyInfo("RUB", "Russian Ruble", "₽", "Russia"),
    CurrencyInfo("AED", "UAE Dirham", "د.إ", "UAE"),
    CurrencyInfo("SAR", "Saudi Riyal", "﷼", "Saudi Arabia"),
    CurrencyInfo("THB", "Thai Baht", "฿", "Thailand"),
    CurrencyInfo("IDR", "Indonesian Rupiah", "Rp", "Indonesia"),
    CurrencyInfo("MYR", "Malaysian Ringgit", "RM", "Malaysia"),
    CurrencyInfo("PHP", "Philippine Peso", "₱", "Philippines"),
    CurrencyInfo("VND", "Vietnamese Dong", "₫", "Vietnam"),
    CurrencyInfo("UAH", "Ukrainian Hryvnia", "₴", "Ukraine"),
    CurrencyInfo("ILS", "Israeli Shekel", "₪", "Israel"),
    CurrencyInfo("EGP", "Egyptian Pound", "£", "Egypt"),
    CurrencyInfo("NGN", "Nigerian Naira", "₦", "Nigeria"),
    CurrencyInfo("KES", "Kenyan Shilling", "KSh", "Kenya"),
    CurrencyInfo("GHS", "Ghanaian Cedi", "₵", "Ghana"),
)
