package com.dv.moneym.core.model

import kotlinx.serialization.Serializable

@Serializable
enum class Icon(val key: String) {
    Plus("plus"),
    Close("close"),
    Search("search"),
    ChevronLeft("chevron_left"),
    ChevronRight("chevron_right"),
    ChevronDown("chevron_down"),
    Check("check"),
    Trash("trash"),
    Backspace("backspace"),
    FaceId("face_id"),
    Fingerprint("fingerprint"),
    Lock("lock"),
    Sun("sun"),
    Moon("moon"),
    Sliders("sliders"),
    Globe("globe"),
    List("list"),
    Download("download"),
    Folder("folder"),
    ArrowUp("arrow_up"),
    ArrowDown("arrow_down"),
    Info("info"),
    Heart("heart"),
    Film("film"),
    Car("car"),
    Bolt("bolt"),
    Basket("basket"),
    Utensils("utensils"),
    Home("home"),
    Bag("bag"),
    Tag("tag"),
    Banknote("banknote"),
    Gift("gift"),
    Calendar("calendar"),
    DragHandle("drag_handle"),
    Settings("settings"),
    Chart("chart"),
    Calculator("calculator"),
    Wallet("wallet"),
    Cart("cart"),
    Restaurant("restaurant"),
    HeartPulse("heart_pulse"),
    Health("health"),
    PlayCircle("play_circle"),
    Bank("bank"),
    Dots("dots"),
    Edit("edit"),
    Eye("eye"),
    EyeOff("eye_off"),
    Sparkles("sparkles"),
    Sync("sync"),
    CloudSync("cloud_sync"),
    Warning("warning"),
    Bell("bell"),
    Coffee("coffee"),
    Plane("plane"),
    Book("book"),
    Paw("paw"),
    MedicalCross("medical_cross"),
    Fuel("fuel"),
    Phone("phone"),
    Dumbbell("dumbbell"),
    Shirt("shirt"),
    ;

    companion object {
        fun fromKey(key: String): Icon? = entries.find { it.key == key }
        fun fromKeyOrDefault(key: String, default: Icon = Tag): Icon = fromKey(key) ?: default
    }
}
